In [6]:
import numpy as np 

arrayentero = np.array([1,2,3,4,5,6,7,8,9,10])
formaarray = arrayentero.shape
print(formaarray)
largoarray  = len(arrayentero)
print(largoarray)

(10,)
10


In [2]:
array1d = np.array([1, 2, 3, 4, 5])

In [9]:
array2d = np.array([[1,2,3],[4,5,6]])
print(array2d)
formaarray2d= array2d.shape
print(formaarray2d)
largoarray2d = len(array2d)
print(largoarray2d)



[[1 2 3]
 [4 5 6]]
(2, 3)
2


In [18]:
#CONCATENAR 
arrayprueba = [[1,2],[3,4]]
arrayprueba2= [[1,2],[3,4]]
type(np.concatenate([arrayprueba,arrayprueba2]))


numpy.ndarray

In [24]:
#Manipulacion de arrays

array1 = [1,2,3,4,5]
array2 = [6,7,8,9,10]

arrayconcatenado = np.concatenate([array1,array2])
print(arrayconcatenado)


arrayoriginal = np.array([1,2,3,4,5,6])
arrayreshape = arrayoriginal.reshape(2,3)
print(arrayreshape)

[ 1  2  3  4  5  6  7  8  9 10]
[[1 2 3]
 [4 5 6]]


In [27]:
#Maniuplacion de array
a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])

sumaab= a + b 
print(sumaab)

productoAB = a*b
print(productoAB)

[[ 6  8]
 [10 12]]
[[ 5 12]
 [21 32]]


In [46]:
import numpy as np
arraynuevo= np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arraynuevo)
type(arraynuevo)


arraynuevo[1]

[[1 2 3]
 [4 5 6]
 [7 8 9]]


array([4, 5, 6])

In [56]:
#SLICING


arraynuevo[1, :]



array([4, 5, 6])

In [74]:
arraynuevo[:2,:2]

array([[1, 2],
       [4, 5]])

In [20]:
#PARA COLUMNA

array2d[:,2]

array([3, 6, 9])

In [21]:
array2d[:2, : 2]

array([[1, 2],
       [4, 5]])

In [76]:
#Condicion Booleana

arraynuevo >4

array([[False, False, False],
       [False,  True,  True],
       [ True,  True,  True]])

In [81]:
arraynuevo % 2 == 0

array([[False,  True, False],
       [ True, False,  True],
       [False,  True, False]])

In [83]:
#Segmentacion e Indexacion

numeros = np.array([1,2,3,4,5,6,7,8,9,10])
quinto_elemento = numeros[5]
print(quinto_elemento)


6


In [85]:
matriz = np.array([[1,2,3],[4,5,6],[7,8,9]])
segunda_fila = matriz[1:2]
print(segunda_fila)

[[4 5 6]]


In [86]:
matriz = np.array([[1,2,3],[4,5,6],[7,8,9]])
pares = matriz % 2 == 0 
impares = matriz % 2 == 1

print(pares)
print(impares)

[[False  True False]
 [ True False  True]
 [False  True False]]
[[ True False  True]
 [False  True False]
 [ True False  True]]


In [87]:
#Forma y Estructura de los Arrays 

array_original = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
array_reshape = array_original.reshape(3,4)
print(array_reshape)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [91]:
array_original2 = np.array([[1,2,3],[4,5,6]])
array_modificado = array_original2.transpose()
print(array_modificado)


[[1 4]
 [2 5]
 [3 6]]


In [92]:
array_original2 = np.array([[1,2,3],[4,5,6]])
array_modificado = array_original2.flatten()
print(array_modificado)

[1 2 3 4 5 6]
